import type { Car } from '@/types';

export const cars: Car[] = [
  {
    id: 'c1',
    slug: 'bmw-3-series-2024',
    name: 'BMW 3 Series',
    brand: 'BMW',
    category: 'Luxury',
    price: 245000,
    downPayment: 49000,
    emiFrom: 3799,
    tenure: 60,
    year: 2024,
    fuel: 'Petrol',
    transmission: 'Automatic',
    mileage: '14.5 km/l',
    seating: 5,
    engine: '2.0L Turbo',
    power: '255 bhp',
    images: [
      'https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=1600&q=80',
      'https://images.unsplash.com/photo-1542362567-b07e54358753?auto=format&fit=crop&w=1600&q=80',
      'https://images.unsplash.com/photo-1494976388531-d1058494cdd8?auto=format&fit=crop&w=1600&q=80',
    ],
    features: [
      'Panoramic Sunroof',
      'Adaptive Cruise Control',
      'Wireless Apple CarPlay',
      'Heated & Ventilated Seats',
      'Harman Kardon Audio',
      '360° Camera',
    ],
    description:
      'The BMW 3 Series defines the sport sedan segment. Razor-sharp handling meets refined luxury — now available with industry-leading installment plans across the UAE.',
    badge: 'Hot',
    featured: true,
  },
  {
    id: 'c2',
    slug: 'mercedes-c-class-2024',
    name: 'Mercedes-Benz C-Class',
    brand: 'Mercedes-Benz',
    category: 'Luxury',
    price: 279000,
    downPayment: 55800,
    emiFrom: 4329,
    tenure: 60,
    year: 2024,
    fuel: 'Petrol',
    transmission: 'Automatic',
    mileage: '13.8 km/l',
    seating: 5,
    engine: '1.5L Turbo + EQ Boost',
    power: '201 bhp',
    images: [
      'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?auto=format&fit=crop&w=1600&q=80',
      'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&w=1600&q=80',
    ],
    features: [
      'MBUX Hyperscreen',
      'Burmester 3D Audio',
      'Air Body Control',
      'Heads-Up Display',
      'Massage Seats',
      'Ambient Lighting',
    ],
    description:
      'Mercedes-Benz reimagined. The C-Class brings flagship S-Class technology to a more accessible sedan with smart finance options.',
    badge: 'New',
    featured: true,
  },
  {
    id: 'c3',
    slug: 'audi-q5-2024',
    name: 'Audi Q5',
    brand: 'Audi',
    category: 'SUV',
    price: 329000,
    downPayment: 65800,
    emiFrom: 5099,
    tenure: 60,
    year: 2024,
    fuel: 'Petrol',
    transmission: 'Automatic',
    mileage: '12.2 km/l',
    seating: 5,
    engine: '2.0L TFSI',
    power: '261 bhp',
    images: [
      'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&w=1600&q=80',
      'https://images.unsplash.com/photo-1614026480418-bd11fde5f1ab?auto=format&fit=crop&w=1600&q=80',
    ],
    features: [
      'Quattro All-Wheel Drive',
      'Virtual Cockpit Plus',
      'Bang & Olufsen Sound',
      'Adaptive Air Suspension',
      'Matrix LED Headlights',
      'Wireless Charging',
    ],
    description:
      'Confident on every terrain. The Audi Q5 combines German engineering with practical luxury, now with flexible UAE finance plans.',
    badge: 'Popular',
    featured: true,
  },
  {
    id: 'c4',
    slug: 'tesla-model-3-2024',
    name: 'Tesla Model 3',
    brand: 'Tesla',
    category: 'Electric',
    price: 189000,
    downPayment: 37800,
    emiFrom: 2929,
    tenure: 60,
    year: 2024,
    fuel: 'Electric',
    transmission: 'Automatic',
    mileage: '491 km range',
    seating: 5,
    engine: 'Dual Motor AWD',
    power: '346 bhp',
    images: [
      'https://images.unsplash.com/photo-1560958089-b8a1929cea89?auto=format&fit=crop&w=1600&q=80',
      'https://images.unsplash.com/photo-1617788138017-80ad40651399?auto=format&fit=crop&w=1600&q=80',
    ],
    features: [
      'Autopilot Included',
      '491 km Range',
      '15" Touchscreen',
      'Glass Roof',
      'Premium Connectivity',
      'Sentry Mode',
    ],
    description:
      'The future of driving, today. Tesla Model 3 with autonomous capabilities, blistering acceleration, and zero emissions — perfect for UAE roads.',
    badge: 'Hot',
    featured: true,
  },
  {
    id: 'c5',
    slug: 'toyota-land-cruiser-2024',
    name: 'Toyota Land Cruiser',
    brand: 'Toyota',
    category: 'SUV',
    price: 299000,
    downPayment: 59800,
    emiFrom: 4639,
    tenure: 60,
    year: 2024,
    fuel: 'Petrol',
    transmission: 'Automatic',
    mileage: '9.8 km/l',
    seating: 7,
    engine: '3.5L V6 Twin-Turbo',
    power: '409 bhp',
    images: [
      'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=1600&q=80',
      'https://images.unsplash.com/photo-1567343483496-bb84a8d62afc?auto=format&fit=crop&w=1600&q=80',
    ],
    features: [
      'Full-Time 4WD',
      'Multi-Terrain Select',
      'JBL Premium Audio',
      'Cooled Box',
      'Heads-Up Display',
      '360° Camera',
    ],
    description:
      'The UAE\'s favorite SUV. Conquer the dunes on weekends and Sheikh Zayed Road on weekdays — with finance plans built for both.',
    badge: 'Best Deal',
    featured: true,
  },
  {
    id: 'c6',
    slug: 'nissan-patrol-2024',
    name: 'Nissan Patrol',
    brand: 'Nissan',
    category: 'SUV',
    price: 269000,
    downPayment: 53800,
    emiFrom: 4179,
    tenure: 60,
    year: 2024,
    fuel: 'Petrol',
    transmission: 'Automatic',
    mileage: '8.5 km/l',
    seating: 7,
    engine: '5.6L V8',
    power: '400 bhp',
    images: [
      'https://images.unsplash.com/photo-1567343483496-bb84a8d62afc?auto=format&fit=crop&w=1600&q=80',
    ],
    features: [
      'Intelligent 4WD',
      'Hydraulic Body Control',
      'BOSE Premium Audio',
      'Quilted Leather Seats',
      'Around View Monitor',
      'Cooled Cup Holders',
    ],
    description:
      'King of the desert. The Patrol delivers V8 muscle and full-size comfort, with finance terms that match its ambition.',
    badge: 'Popular',
    featured: false,
  },
  {
    id: 'c7',
    slug: 'hyundai-tucson-2024',
    name: 'Hyundai Tucson',
    brand: 'Hyundai',
    category: 'SUV',
    price: 105000,
    downPayment: 21000,
    emiFrom: 1629,
    tenure: 60,
    year: 2024,
    fuel: 'Petrol',
    transmission: 'Automatic',
    mileage: '13.5 km/l',
    seating: 5,
    engine: '2.0L MPi',
    power: '156 bhp',
    images: [
      'https://images.unsplash.com/photo-1494976388531-d1058494cdd8?auto=format&fit=crop&w=1600&q=80',
      'https://images.unsplash.com/photo-1502877338535-766e1452684a?auto=format&fit=crop&w=1600&q=80',
    ],
    features: [
      'Panoramic Sunroof',
      'Ventilated Seats',
      'Wireless CarPlay',
      'BOSE 8-Speaker System',
      'Heated Steering Wheel',
      'Smart Power Tailgate',
    ],
    description:
      'Bold styling, generous features, smart price. Tucson brings premium SUV vibes within reach of every UAE family.',
    badge: 'Best Deal',
    featured: false,
  },
  {
    id: 'c8',
    slug: 'porsche-911-2024',
    name: 'Porsche 911 Carrera',
    brand: 'Porsche',
    category: 'Sports',
    price: 849000,
    downPayment: 169800,
    emiFrom: 13149,
    tenure: 60,
    year: 2024,
    fuel: 'Petrol',
    transmission: 'Automatic',
    mileage: '11.2 km/l',
    seating: 4,
    engine: '3.0L Twin-Turbo Flat-6',
    power: '385 bhp',
    images: [
      'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1600&q=80',
      'https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?auto=format&fit=crop&w=1600&q=80',
    ],
    features: [
      'PASM Sport Suspension',
      'Sport Chrono Package',
      'BOSE Surround Sound',
      'Adaptive Sports Seats',
      'Launch Control',
      'Carbon Ceramic Brakes',
    ],
    description:
      'The benchmark sports car. 0-100 in 4.2 seconds — with bespoke finance structuring for the UAE\'s most discerning drivers.',
    badge: 'New',
    featured: true,
  },
];

// NOTE: This array is the SEED / fallback dataset. Live data is served from the
// database via `@/server/cars`, which falls back to this list when no DB is set.
