import type { Car } from '@/types';

export const cars: Car[] = [
  {
    id: 'c1',
    slug: 'bmw-3-series-2024',
    name: 'BMW 3 Series',
    brand: 'BMW',
    category: 'Luxury',
    price: 5499000,
    downPayment: 549900,
    emiFrom: 84999,
    tenure: 60,
    year: 2024,
    fuel: 'Petrol',
    transmission: 'Automatic',
    mileage: '14.5 km/l',
    seating: 5,
    engine: '2.0L Turbo',
    power: '255 bhp',
    images: [
      'https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=1600&q=80',
      'https://images.unsplash.com/photo-1542362567-b07e54358753?auto=format&fit=crop&w=1600&q=80',
      'https://images.unsplash.com/photo-1494976388531-d1058494cdd8?auto=format&fit=crop&w=1600&q=80',
    ],
    features: [
      'Panoramic Sunroof',
      'Adaptive Cruise Control',
      'Wireless Apple CarPlay',
      'Heated Leather Seats',
      'Harman Kardon Audio',
      '360° Camera',
    ],
    description:
      'The BMW 3 Series defines the sport sedan segment. Razor-sharp handling meets refined luxury — now available with industry-leading EMI plans.',
    badge: 'Hot',
    featured: true,
  },
  {
    id: 'c2',
    slug: 'mercedes-c-class-2024',
    name: 'Mercedes-Benz C-Class',
    brand: 'Mercedes-Benz',
    category: 'Luxury',
    price: 6299000,
    downPayment: 629900,
    emiFrom: 97499,
    tenure: 60,
    year: 2024,
    fuel: 'Petrol',
    transmission: 'Automatic',
    mileage: '13.8 km/l',
    seating: 5,
    engine: '1.5L Turbo + EQ Boost',
    power: '201 bhp',
    images: [
      'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?auto=format&fit=crop&w=1600&q=80',
      'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&w=1600&q=80',
    ],
    features: [
      'MBUX Hyperscreen',
      'Burmester 3D Audio',
      'Air Body Control',
      'Heads-Up Display',
      'Massage Seats',
      'Ambient Lighting',
    ],
    description:
      'Mercedes-Benz reimagined. The C-Class brings flagship S-Class technology to a more accessible sedan with smart EMI options.',
    badge: 'New',
    featured: true,
  },
  {
    id: 'c3',
    slug: 'audi-q5-2024',
    name: 'Audi Q5',
    brand: 'Audi',
    category: 'SUV',
    price: 7499000,
    downPayment: 749900,
    emiFrom: 115999,
    tenure: 60,
    year: 2024,
    fuel: 'Diesel',
    transmission: 'Automatic',
    mileage: '16.2 km/l',
    seating: 5,
    engine: '2.0L TDI',
    power: '201 bhp',
    images: [
      'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&w=1600&q=80',
      'https://images.unsplash.com/photo-1614026480418-bd11fde5f1ab?auto=format&fit=crop&w=1600&q=80',
    ],
    features: [
      'Quattro All-Wheel Drive',
      'Virtual Cockpit Plus',
      'Bang & Olufsen Sound',
      'Adaptive Air Suspension',
      'Matrix LED Headlights',
      'Wireless Charging',
    ],
    description:
      'Confident on every terrain. The Audi Q5 combines German engineering with practical luxury, now with flexible EMI plans.',
    badge: 'Popular',
    featured: true,
  },
  {
    id: 'c4',
    slug: 'tesla-model-3-2024',
    name: 'Tesla Model 3',
    brand: 'Tesla',
    category: 'Electric',
    price: 4699000,
    downPayment: 469900,
    emiFrom: 72499,
    tenure: 60,
    year: 2024,
    fuel: 'Electric',
    transmission: 'Automatic',
    mileage: '491 km range',
    seating: 5,
    engine: 'Dual Motor AWD',
    power: '346 bhp',
    images: [
      'https://images.unsplash.com/photo-1560958089-b8a1929cea89?auto=format&fit=crop&w=1600&q=80',
      'https://images.unsplash.com/photo-1617788138017-80ad40651399?auto=format&fit=crop&w=1600&q=80',
    ],
    features: [
      'Autopilot Included',
      '491 km Range',
      '15" Touchscreen',
      'Glass Roof',
      'Premium Connectivity',
      'Sentry Mode',
    ],
    description:
      'The future of driving, today. Tesla Model 3 with autonomous capabilities, blistering acceleration, and zero emissions.',
    badge: 'Hot',
    featured: true,
  },
  {
    id: 'c5',
    slug: 'hyundai-creta-2024',
    name: 'Hyundai Creta',
    brand: 'Hyundai',
    category: 'SUV',
    price: 1599000,
    downPayment: 159900,
    emiFrom: 24999,
    tenure: 60,
    year: 2024,
    fuel: 'Petrol',
    transmission: 'Automatic',
    mileage: '17.5 km/l',
    seating: 5,
    engine: '1.5L Turbo GDi',
    power: '158 bhp',
    images: [
      'https://images.unsplash.com/photo-1494976388531-d1058494cdd8?auto=format&fit=crop&w=1600&q=80',
      'https://images.unsplash.com/photo-1502877338535-766e1452684a?auto=format&fit=crop&w=1600&q=80',
    ],
    features: [
      'Bose 8-Speaker System',
      'Panoramic Sunroof',
      'ADAS Level 2',
      'Ventilated Seats',
      'Wireless Charging',
      'Smart Connect',
    ],
    description:
      'India\'s best-selling SUV. Loaded with features at a price that makes EMIs effortless.',
    badge: 'Best Deal',
    featured: true,
  },
  {
    id: 'c6',
    slug: 'mahindra-thar-2024',
    name: 'Mahindra Thar',
    brand: 'Mahindra',
    category: 'SUV',
    price: 1799000,
    downPayment: 179900,
    emiFrom: 27999,
    tenure: 60,
    year: 2024,
    fuel: 'Diesel',
    transmission: 'Manual',
    mileage: '15.2 km/l',
    seating: 4,
    engine: '2.2L mHawk',
    power: '130 bhp',
    images: [
      'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=1600&q=80',
      'https://images.unsplash.com/photo-1567343483496-bb84a8d62afc?auto=format&fit=crop&w=1600&q=80',
    ],
    features: [
      '4WD with Low Range',
      'Removable Hard Top',
      'Off-road Cruise Control',
      'Touchscreen Infotainment',
      'All-terrain Tyres',
      'Hill Hold Assist',
    ],
    description:
      'Built for adventure. The legendary Thar conquers any road — and your monthly budget.',
    badge: 'Popular',
    featured: false,
  },
  {
    id: 'c7',
    slug: 'maruti-baleno-2024',
    name: 'Maruti Baleno',
    brand: 'Maruti Suzuki',
    category: 'Hatchback',
    price: 799000,
    downPayment: 79900,
    emiFrom: 12499,
    tenure: 60,
    year: 2024,
    fuel: 'Petrol',
    transmission: 'Manual',
    mileage: '22.9 km/l',
    seating: 5,
    engine: '1.2L K-Series',
    power: '89 bhp',
    images: [
      'https://images.unsplash.com/photo-1471444928139-48c5bf5173f8?auto=format&fit=crop&w=1600&q=80',
    ],
    features: [
      'Heads-Up Display',
      '360° Camera',
      'SmartPlay Pro',
      'Hill Hold Assist',
      'Cruise Control',
      'LED Projector Headlamps',
    ],
    description:
      'The premium hatchback that started it all. Best-in-class mileage with fully-loaded variants.',
    badge: 'Best Deal',
    featured: false,
  },
  {
    id: 'c8',
    slug: 'porsche-911-2024',
    name: 'Porsche 911 Carrera',
    brand: 'Porsche',
    category: 'Sports',
    price: 18999000,
    downPayment: 1899900,
    emiFrom: 293999,
    tenure: 60,
    year: 2024,
    fuel: 'Petrol',
    transmission: 'Automatic',
    mileage: '11.2 km/l',
    seating: 4,
    engine: '3.0L Twin-Turbo Flat-6',
    power: '385 bhp',
    images: [
      'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1600&q=80',
      'https://images.unsplash.com/photo-1611821064430-0d40291922d2?auto=format&fit=crop&w=1600&q=80',
    ],
    features: [
      'PASM Sport Suspension',
      'Sport Chrono Package',
      'BOSE Surround Sound',
      'Adaptive Sports Seats',
      'Launch Control',
      'Carbon Ceramic Brakes',
    ],
    description:
      'The benchmark sports car. 0-100 in 4.2 seconds — and now with bespoke EMI structuring for connoisseurs.',
    badge: 'New',
    featured: true,
  },
];

export const getCarBySlug = (slug: string) => cars.find((c) => c.slug === slug);
export const getFeaturedCars = () => cars.filter((c) => c.featured);
export const getCarsByCategory = (cat: string) =>
  cars.filter((c) => c.category === cat);
export const getRelatedCars = (slug: string, limit = 3) => {
  const car = getCarBySlug(slug);
  if (!car) return [];
  return cars
    .filter((c) => c.slug !== slug && c.category === car.category)
    .slice(0, limit);
};
