import type { Testimonial } from '@/types';

export const testimonials: Testimonial[] = [
  {
    id: 't1',
    name: 'Ahmed Al Mansoori',
    role: 'Government Officer, Abu Dhabi',
    avatar: '/testimonials/t1.jpg',
    rating: 5,
    text: 'Got my Toyota Land Cruiser within 36 hours. Zero hidden charges, and the monthly installment is exactly what was quoted. Their team made the entire process effortless.',
    car: 'Toyota Land Cruiser',
  },
  {
    id: 't2',
    name: 'Sarah Thompson',
    role: 'Marketing Director, Dubai',
    avatar: '/testimonials/t2.jpg',
    rating: 5,
    text: 'I was nervous about financing a luxury car as an expat. Buy&Drive Cars made it feel like a regular purchase. Transparent rates, friendly staff, and a brand-new BMW in my driveway within a week.',
    car: 'BMW 3 Series',
  },
  {
    id: 't3',
    name: 'Rohan Iyer',
    role: 'Entrepreneur, Dubai Marina',
    avatar: '/testimonials/t3.jpg',
    rating: 5,
    text: 'Switched to EV without any upfront stress. The green-finance plan saved me almost AED 12,000 over the loan period. Highly recommend for anyone considering a Tesla in the UAE.',
    car: 'Tesla Model 3',
  },
  {
    id: 't4',
    name: 'Fatima Al Hashimi',
    role: 'Architect, Sharjah',
    avatar: '/testimonials/t4.jpg',
    rating: 5,
    text: 'After being rejected by 2 banks due to my freelance income, Buy&Drive Cars approved my finance in a single day. They genuinely understand the UAE market and self-employed customers.',
    car: 'Nissan Patrol',
  },
];

export const brands = [
  { name: 'BMW', logo: '/brands/bmw.svg' },
  { name: 'Mercedes-Benz', logo: '/brands/mercedes.svg' },
  { name: 'Audi', logo: '/brands/audi.svg' },
  { name: 'Porsche', logo: '/brands/porsche.svg' },
  { name: 'Tesla', logo: '/brands/tesla.svg' },
  { name: 'Toyota', logo: '/brands/toyota.svg' },
  { name: 'Nissan', logo: '/brands/nissan.svg' },
  { name: 'Lexus', logo: '/brands/lexus.svg' },
  { name: 'Hyundai', logo: '/brands/hyundai.svg' },
  { name: 'Honda', logo: '/brands/honda.svg' },
  { name: 'JAC', logo: '/brands/jac.svg' },
  { name: 'Mitsubishi', logo: '/brands/mitsubishi.svg' },
  { name: 'Chevrolet', logo: '/brands/chevrolet.svg' },
  { name: 'Kia', logo: '/brands/kia.svg' },
  { name: 'Haval', logo: '/brands/haval.svg' },
  { name: 'MG', logo: '/brands/mg.svg' },
  { name: 'Suzuki', logo: '/brands/suzuki.svg' },
  { name: 'Jetour', logo: '/brands/jetour.svg' },
];
